version: '3.3'

services:
  feedbacky-server:
    environment:
      # ========================================================
      # =   ENVIRONMENT VARIABLES CONFIGURATION BEGINS HERE    =
      # ========================================================

      # >>           CLIENT SIDE VARIABLES CONFIGURATION       <<
      # Domain or IP address where Feedbacky is hosted, CLIENT_APP_PORT is required here if you don't use port 80 (web port) or domain
      REACT_APP_SERVER_IP_ADDRESS: http://example.com
      # Name of your self hosted Feedbacky service
      REACT_APP_SERVICE_NAME: Feedbacky
      # Link to default user avatar image, use %nick% placeholder to replace with User nickname
      REACT_APP_DEFAULT_USER_AVATAR: https://static.plajer.xyz/avatar/generator/%nick%

      # >>            GENERAL VARIABLES CONFIGURATION          <<
      # Port where client application will run, if this port is used replace it with different one
      CLIENT_APP_PORT: 8090
      # Port where server application will run, if this port is used replace it with different one
      SERVER_APP_PORT: 8095
      # Secret token for authentication purposes, you can generate one here https://www.grc.com/passwords.htm
      JWT_SECRET: secretPass

      # >>         SQL DATABASE VARIABLES CONFIGURATION        <<
      # Database credentials
      MYSQL_USERNAME: username
      MYSQL_PASSWORD: passwd
      # Replace <ip_address> <port> and <database_name> with proper values
      MYSQL_URL: jdbc:mysql://<ip_address>:<port>/<database_name>?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8

      # >>             LOGIN INTEGRATIONS CONFIGURATION        <<
      # Feedbacky is passwordless and relies on 3rd party providers to log in, please enable at least 1 of providers below.
      # All filled values for each OAuth application will count as an enabled login integration.

      # Discord (https://discordapp.com/) login integration enabled
      # To create OAuth application go here https://discordapp.com/developers/applications
      OAUTH_DISCORD_REDIRECT_URI: ""
      OAUTH_DISCORD_CLIENT_ID: ""
      OAUTH_DISCORD_CLIENT_SECRET: ""
      # Allow users to log in just using email address.
      SETTINGS_MAIL_LOGIN_ENABLED: false

      # For Google, GitHub, GitLab and other OAuth integrations please refer to https://docs.feedbacky.net and add any variables manually.

      # >>       MAIL SENDING FEATURE VARIABLES CONFIGURATION (optional)      <<
      # Name of mail sender
      MAIL_SENDER: Feedbacky <no-reply@feedbacky.net>
      # Currently available mail services:
      # * mailgun - https://www.mailgun.com/ (credit card required to set up account) (5k mails for 3 months, then $0.80 per 1k mails)
      # * sendgrid - https://sendgrid.com/ (100 mails per day)
      # * smtp - your own SMTP server for sending mails
      # * "" (blank) - for no mail configuration
      MAIL_SERVICE_TYPE: ""
      # API key for mail service selected above (not for SMTP)
      MAIL_SERVICE_API_KEY: ""
      # API url for mail service
      # For Mailgun: https://api.mailgun.net/v3/<YOUR DOMAIN>/messages
      # For Sendgrid: https://api.sendgrid.com/v3/mail/send
      MAIL_SERVICE_API_BASE_URL: ""
      # SMTP server credentials
      MAIL_SMTP_USERNAME: username
      MAIL_SMTP_PASSWORD: passwd
      MAIL_SMTP_HOST: host.com
      MAIL_SMTP_PORT: 587

      # >>        IMAGES COMPRESSION VARIABLES CONFIGURATION (optional)       <<
      # Is image compression for images enabled? If yes credentials below must be valid.
      IMAGE_COMPRESSION_ENABLED: false
      # Currently available compressors:
      # * cheetaho - https://cheetaho.com/ (free 500 compressions per month)
      IMAGE_COMPRESSION_TYPE: cheetaho
      # API key from https://cheetaho.com/ service
      IMAGE_COMPRESSION_CHEETAHO_API_KEY: apiKey

      # ========================================================
      # =     ENVIRONMENT VARIABLES CONFIGURATION ENDS HERE    =
      # ========================================================
    container_name: feedbacky-server
    ports:
      - '${SERVER_APP_PORT}:8080'
    volumes:
      - feedbacky-data:/storage-data
    image: plajer/feedbacky-server
    restart: always
  feedbacky-client:
    container_name: feedbacky-client
    environment:
      REACT_APP_SERVER_IP_ADDRESS: ${REACT_APP_SERVER_IP_ADDRESS}
      REACT_APP_SERVICE_NAME: ${REACT_APP_SERVICE_NAME}
      REACT_APP_DEFAULT_USER_AVATAR: ${REACT_APP_DEFAULT_USER_AVATAR}
    ports:
      - '${CLIENT_APP_PORT}:80'
    links:
      - feedbacky-server
    volumes:
      - feedbacky-data:/storage-data
    image: plajer/feedbacky-proxy
    restart: always

volumes:
  feedbacky-data: